### ISSUE TITLE
如果 newProviderAPI 使用 address ，那么config 使用 file 实例化。则获取不到config内容

### ISSUE THREAD

**Issue by yanshinian** [polarismesh/polaris-go#107]
**Describe the bug**
如果 newProviderAPI 使用 address ，那么config 使用 file 实例化。则获取不到config内容。
但是如果newProviderAPi使用file 实例化。那么ConfigAPI就可以获取到内容了。

**Comment by chuntaojun** [comment]
已经解决，这个是原来的配置中心设计存在问题，最新的版本已经修复
