### ISSUE TITLE
polaris-go 与 grpc-go-polaris 引用的 specification 版本不一致

### ISSUE THREAD

**Issue by WTIFS** [polarismesh/polaris-go#158]
**Describe the bug**
polaris-go v1.5.1 使用的 specification 版本为 v1.3.2-alpha.2
grpc-go-polaris v1.13.1 使用的 specification 版本为 v1.3.2-alpha.5
业务项目中如果使用 v1.3.2-alpha.2，执行 go mod tidy 时报错
如果使用 v1.3.2-alpha.5，编译时会报错：
<img width="1352" alt="image" src="https://github.com/polarismesh/polaris-go/assets/9314475/c972e03a-cf84-44d1-aa01-fb3d183ecd9a">

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**

- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by tsingsun** [comment]
这个问题也考虑一起解决一下.
Deprecated module github.com/golang/protobuf.
Deprecation notice: Use the "google.golang.org/protobuf" module instead.

**Comment by houseme** [comment]
> 这个问题也考虑一起解决一下. Deprecated module github.com/golang/protobuf. Deprecation notice: Use the "google.golang.org/protobuf" module instead.

这个 `protobuf` 需要等Google官方 `github.com/golang/protobuf` 不依赖 `google.golang.org/protobuf` 就可以处理了。

**Comment by houseme** [comment]
> **Describe the bug** polaris-go v1.5.1 使用的 specification 版本为 v1.3.2-alpha.2 grpc-go-polaris v1.13.1 使用的 specification 版本为 v1.3.2-alpha.5 业务项目中如果使用 v1.3.2-alpha.2，执行 go mod tidy 时报错 如果使用 v1.3.2-alpha.5，编译时会报错： <img alt="image" width="1352" src="https://user-images.githubusercontent.com/9314475/257465092-c972e03a-cf84-44d1-aa01-fb3d183ecd9a.png">
> 
> **To Reproduce** Steps to reproduce the behavior.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Environment**
> 
> * Version: [e.g. v1.0.0]
> * OS: [e.g. CentOS8]
> 
> **Additional context** Add any other context about the problem here.

@WTIFS  考虑来个 pr, 统一 `polaris-go` 和 `grpc-go-polaris`的 `specification` ?

**Comment by WTIFS** [comment]
> > **Describe the bug** polaris-go v1.5.1 使用的 specification 版本为 v1.3.2-alpha.2 grpc-go-polaris v1.13.1 使用的 specification 版本为 v1.3.2-alpha.5 业务项目中如果使用 v1.3.2-alpha.2，执行 go mod tidy 时报错 如果使用 v1.3.2-alpha.5，编译时会报错： <img alt="image" width="1352" src="https://user-images.githubusercontent.com/9314475/257465092-c972e03a-cf84-44d1-aa01-fb3d183ecd9a.png">
> > **To Reproduce** Steps to reproduce the behavior.
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Environment**
> > 
> > * Version: [e.g. v1.0.0]
> > * OS: [e.g. CentOS8]
> > 
> > **Additional context** Add any other context about the problem here.
> 
> @WTIFS 考虑来个 pr, 统一 `polaris-go` 和 `grpc-go-polaris`的 `specification` ?

春少让我提的issue，他说这周看下

**Comment by houseme** [comment]
https://github.com/polarismesh/polaris-go/pull/159

**Comment by chuntaojun** [comment]
already fix
