### ISSUE TITLE
就近路由功能未能跑通

### ISSUE THREAD

**Issue by wereliang** [polarismesh/polaris-go#169]
- 按照https://github.com/polarismesh/polaris-go/blob/main/examples/route/nearby/README-zh.md的demo无法正常跑通
- 修改配置文件同样无法跑通
- 调试跟踪代码发现pkg/config/location.go里头并未对配置文件做初始化的实现
// Init 初始化
func (a *LocationConfigImpl) Init() {
}
- 希望能够提供完整可运行的demo和指引，减少排错调试的时间

**Comment by chuntaojun** [comment]
参见最新 main 分支下的 demo 代码，已经修复
