### ISSUE TITLE
如何设置路由

### ISSUE THREAD

**Issue by degary** [polarismesh/polaris-go#205]
设置的路由规则如下
![route](https://github.com/polarismesh/polaris-go/assets/38277486/b421cc44-4f36-4df5-9cb7-d53249a30290)
使用curl 测试时，执行 
`curl -H "env: dev"   "http://127.0.0.1:18080/echo?ENV=dev"`,返回的结果是兜底route规则设置的结果。

**Comment by chuntaojun** [comment]
新的 demo 已经支持了，可以看下
