### ISSUE TITLE
make polaris-go api more easy to use

### ISSUE THREAD

**Issue by andrewshan** [polarismesh/polaris-go#29]
1. go sdk中api的写法不是很优雅
像api.NewProviderAPI() 这种写法令人感到有带一些迷惑，无法很直观的看出来是哪个api(尤其是接入polaris的多数为server端应用，大部分程序都会去建个api包，用于提供对外的rpc或http api)。可能像zap.NewProduction() 或 gin.Default() 这样，写成 polaris.NewProviderAPI()这样会更直观一点。

https://github.com/polarismesh/polaris/issues/103

**Comment by huyuanxin** [comment]
添加了通过addresses生成的函数。

对与issues的问题，可以通过自定义包名进行实现
import polaris  ....
