### ISSUE TITLE
util.go/IsDir 逻辑有误？

### ISSUE THREAD

**Issue by GuangmingLuo** [polarismesh/polaris-go#31]
**Describe the bug**

file not found = IsDir false 吗？
间接导致 model.IsFile() 检查失效

![image](https://user-images.githubusercontent.com/16001996/148893113-a4d59914-df18-47f1-9200-81e12d21497e.png)

**Comment by andrewshan** [comment]
IsFile的判断缺少了os.Stat的调用，会导致校验不出文件不存在的情况
