### ISSUE TITLE
polaris-server 一开始就挂掉，每次获取限流配置都会超时两秒，阻塞正常业务。

### ISSUE THREAD

**Issue by lzzjingcairensheng** [polarismesh/polaris-go#48]
**Describe the bug**
在使用polaris-go的过程中发现，如果polaris-server一开始就挂掉，获取限流配置每次都是两秒，超时两秒在生产环境是不可接受的。然后我又尝试获取过一次配置之后，再把polaris-server停止，不再有超时现象。我觉得哪怕最开始的时候获取不到限流配置也应该缓存下，后续在更新缓存， 不应该阻塞正常业务。

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**

- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by andrewshan** [comment]
这个主要是缓存机制导致的，因为没有本地缓存，就会去远端尝试拉取，这边做一个重试间隔优化
