### ISSUE TITLE
config 相关配置信息是不是可以按需要配置吗？

### ISSUE THREAD

**Issue by houseme** [polarismesh/polaris-go#61]
## Discussions：https://github.com/polarismesh/polaris/discussions/396

**What is the feature you want to add?**
比如，某个时候只需要注册服务和配置中心功能，这个时候是不是可以设置消费者服务不开启配置？在不需要服务消费服务时，还会生成服务发现的一些文件信息，这样会有点怪怪

**Why do you want to add this feature?**
实现配置信息，可以按需加载。

**Comment by chuntaojun** [comment]
北极星SDK本身存在二次寻址的能力，这个能力需要借助服务发现
