### ISSUE TITLE
根据实例id获取实例信息

### ISSUE THREAD

**Issue by debug-LiXiwen** [polarismesh/polaris-go#64]
**What is the feature you want to add?**
根据实例id获取实例信息
**Why do you want to add this feature?**
在做kitex的实例和北极星实例转换的时候，因为北极星实例信息过多，代码强转无法满足

**Comment by chuntaojun** [comment]
这个我理解，是不是可以一个 struct 实现 北极星 Instance 的定义以及 kitex 对于实例的 interface ？这样子强转应该是不会有问题的

**Comment by debug-LiXiwen** [comment]
> 这个我理解，是不是可以一个 struct 实现 北极星 Instance 的定义以及 kitex 对于实例的 interface ？这样子强转应该是不会有问题的

赞，确实可行
