### ISSUE TITLE
运行circuitbreaker provider demo无法正常执行

### ISSUE THREAD

**Issue by apoyl** [polarismesh/polaris-go#82]
![image](https://user-images.githubusercontent.com/1912452/180392702-c8678d79-010f-4ed2-8953-ed4a62c71d50.png)
错误提示：
# command-line-arguments
.\main.go:106:20: undefined: syscall.SIGUSR1
系统是windows 10

**Comment by chuntaojun** [comment]
目前 demo 没有适配 window 下的场景，可以现在 wsl 里面运行看下
